function biggerIndContributions3 = importfile8(filename, dataLines)
%IMPORTFILE8 Import data from a text file
%  BIGGERINDCONTRIBUTIONS3 = IMPORTFILE8(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  BIGGERINDCONTRIBUTIONS3 = IMPORTFILE8(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  biggerIndContributions3 = importfile8("C:\Users\HP\Desktop\biggerIndContributions3.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Jul-2021 13:40:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Industries", "PercentageContribution"];
opts.VariableTypes = ["categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Industries", "EmptyFieldRule", "auto");

% Import the data
biggerIndContributions3 = readtable(filename, opts);

end