function distribution = importfile12(filename, dataLines)
%IMPORTFILE12 Import data from a text file
%  DISTRIBUTION = IMPORTFILE12(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DISTRIBUTION = IMPORTFILE12(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  distribution = importfile12("C:\Users\HP\Desktop\distribution.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Jul-2021 00:02:46

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Industries", "AdvancedTechnologyUse", "EmergingTechnologyUse"];
opts.VariableTypes = ["categorical", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Industries", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["AdvancedTechnologyUse", "EmergingTechnologyUse"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["AdvancedTechnologyUse", "EmergingTechnologyUse"], "ThousandsSeparator", ",");

% Import the data
distribution = readtable(filename, opts);

end