function advtech = importfile4(filename, dataLines)
%IMPORTFILE4 Import data from a text file
%  ADVTECH = IMPORTFILE4(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  ADVTECH = IMPORTFILE4(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  advtech = importfile4("C:\Users\HP\Desktop\advtech.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Jul-2021 12:51:27

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Industry", "AgricultureForestryFishingAndHunting", "MiningQuarryingAndOilAndGasExtraction", "Utilities", "Construction", "Manufacturing", "WholesaleTrade", "RetailTrade", "TransportationAndWarehousing", "PostalServicesCouriersAndMessengersWarehousingAndStorage7", "InformationAndCulturalIndustries", "FinanceAndInsuranceExcludingMonetaryAuthorities8", "RealEstateAndRentalAndLeasing", "ProfessionalScientificAndTechnicalServices", "ManagementOfCompaniesAndEnterprises", "AdministrativeAndSupportWasteManagementAndRemediationServices"];
opts.VariableTypes = ["categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Industry", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["AgricultureForestryFishingAndHunting", "MiningQuarryingAndOilAndGasExtraction", "Utilities", "Construction", "Manufacturing", "WholesaleTrade", "RetailTrade", "TransportationAndWarehousing", "PostalServicesCouriersAndMessengersWarehousingAndStorage7", "InformationAndCulturalIndustries", "FinanceAndInsuranceExcludingMonetaryAuthorities8", "RealEstateAndRentalAndLeasing", "ProfessionalScientificAndTechnicalServices", "ManagementOfCompaniesAndEnterprises", "AdministrativeAndSupportWasteManagementAndRemediationServices"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["AgricultureForestryFishingAndHunting", "MiningQuarryingAndOilAndGasExtraction", "Utilities", "Construction", "Manufacturing", "WholesaleTrade", "RetailTrade", "TransportationAndWarehousing", "PostalServicesCouriersAndMessengersWarehousingAndStorage7", "InformationAndCulturalIndustries", "FinanceAndInsuranceExcludingMonetaryAuthorities8", "RealEstateAndRentalAndLeasing", "ProfessionalScientificAndTechnicalServices", "ManagementOfCompaniesAndEnterprises", "AdministrativeAndSupportWasteManagementAndRemediationServices"], "ThousandsSeparator", ",");

% Import the data
advtech = readtable(filename, opts);

end